name: Build and Depoly in AWS ec2

on:
  push:
    branches: [ depoly ]

# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BE

    steps:
      # Java Spring Gradle
      - uses: actions/checkout@v3
      
      - name: Spring - Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Spring - Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Spring - Test and Build with Gradle
        run: ./gradlew clean build

      # Docker
      - name: Docker - Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker - Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./BE
          push: true
          tags: jeremy0405/airbnb:latest

  depoly:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Depoly in AWS ec2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker pull jeremy0405/airbnb:latest
            sudo docker stop airbnb-spring-server && sudo docker rm airbnb-spring-server
            sudo docker run -d --name airbnb-spring-server -p 8080:8080 jeremy0405/airbnb:latest

